key: Suicide_Model
kind: model
iter: 0
tree: 8cfa3b55fff54f708fe229461fecc0db
target_path: ./Data/models/
hash: e70553803d5c99d65809d38895bb39839349454f
size: 16778151
db_key: train_model_Suicide_Model
model_file: Suicide_Model.pkl
framework: ''
producer:
  name: train_model
  kind: run
  uri: default/8cfa3b55fff54f708fe229461fecc0db
  owner: ahmadkhan242
sources:
- name: input_ds
  path: ./Data/data/suicide_dataset_transformed.csv
project: default
updated: '2021-07-04T10:33:31.364994+00:00'
